### ISSUE TITLE
docker image does not exist

### ISSUE THREAD

**Issue by fangmuke** [Devo919/Gewechat#1]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/17edb8b4-9a6f-437b-8019-5020d519a980">

docker engine setting (The URL is automatically escaped, no problem )
<img width="540" alt="image" src="https://github.com/user-attachments/assets/d9bd1859-1758-4fdc-b6ec-934f5d432ff4">

**Comment by Devo919** [comment]
Docker已经重新上传

房木可 ***@***.***>于2024年7月24日 周三01:05写道：
