### ISSUE TITLE
镜像能否支持debian或者mac，如果不同省份的服务器目前输入验证码参数也是提示登录失败

### ISSUE THREAD

**Issue by mikoshu** [Devo919/Gewechat#18]
镜像能否支持debian或者mac，如果不同省份的服务器目前输入验证码参数也是提示登录失败
目前使用mac m系列开发 服务器也基本没有我们省份的 太难了目前用外省服务器卡在验证码这一步 传了参数也无法使用

**Comment by edwardzcn-decade** [comment]
https://github.com/Devo919/Gewechat/issues/9#issuecomment-2314774657

参考这个，后面的镜像支持最新的macOS 15.2系统（m4 芯片可以，m2还有个Rst转译的故障
