### ISSUE TITLE
测试收消息的回调函数时发现干扰信息太多，是否可以设置白名单？

### ISSUE THREAD

**Issue by BluerAngala** [Devo919/Gewechat#23]
我的开发环境是 unicloud 云函数。

在测试收消息的函数时，发现后台每时每刻都会有打印消息日志，但是实际上我所需要的是特定人或者特定群的消息。
因为每次调用云函数都会消耗云函数资源，造成严重浪费。

请问是否可以设置白名单？

![Clip_2024-10-15_16-44-30](https://github.com/user-attachments/assets/6e2d84ed-2ce9-481b-93f9-bd4db972637f)

**Comment by poo0ooq** [comment]
这就有点扯了吧，看了一下数据库，保存了30万条微信记录，使用3.72 GB储存，单条记录平均13K。
我这数据记录还是有冗余的，实际单条数据最多10K。

1G流量可以跑到10万条记录。一个微信一天要是跑到5万条记录，估计要被风控了。

如果你非要找个方法，我提供一个思路吧：
加个跳板机做转发，按照TypeName，MsgType就行过滤，需要的转发不需要的丢弃。

*
云函数，237次调用，900G流量，你这是下载站啊。和微信没啥关系了。月1.5万次请求根本不够用。

**Comment by Devo919** [comment]
> 这就有点扯了吧，看了一下数据库，保存了30万条微信记录，使用3.72 GB储存，单条记录平均13K。 我这数据记录还是有冗余的，实际单条数据最多10K。
> 
> 1G流量可以跑到10万条记录。一个微信一天要是跑到5万条记录，估计要被风控了。
> 
> 如果你非要找个方法，我提供一个思路吧： 加个跳板机做转发，按照TypeName，MsgType进行过滤，需要的转发不需要的丢弃。
> 
> 
> 云函数，237次调用，900G流量，你这是下载站啊。和微信没啥关系了。月1.5万次请求根本不够用。

对

**Comment by BluerAngala** [comment]
谢谢。检查了一下，应该是后台配置云函数执行内存设置问题，设置过大导致流量超出。可能是之前跑其他错误设置，已修改。
