### ISSUE TITLE
无法访问系统资源

### ISSUE THREAD

**Issue by Searchld** [Devo919/Gewechat#3]
{
    "ret": 401,
    "msg": "请求访问：/tools/getTokenId，认证失败，无法访问系统资源"
}

**Comment by Searchld** [comment]
> { "ret": 401, "msg": "请求访问：/tools/getTokenId，认证失败，无法访问系统资源" }

![1641721806327_ pic](https://github.com/user-attachments/assets/5446f982-cb74-4e51-a684-7d04a4d1a9b0)

**Comment by aw11100** [comment]
> > { "ret": 401, "msg": "请求访问：/tools/getTokenId，认证失败，无法访问系统资源" }
> 
> ![1641721806327_ pic](https://private-user-images.githubusercontent.com/22090418/351619008-5446f982-cb74-4e51-a684-7d04a4d1a9b0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcwMzMsIm5iZiI6MTcyMTgwNjczMywicGF0aCI6Ii8yMjA5MDQxOC8zNTE2MTkwMDgtNTQ0NmY5ODItY2I3NC00ZTUxLWE2ODQtN2QwNGE0ZDFhOWIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmQzY2UyMWRkMTg3N2RkNGE0MDE2OTllMDIyOTkyMTk2MTk5YjE2NGM1MGRiM2RhOWNiOGUzZjdlYjg1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cDmBMfvItYlRbx6v_vhaCb66CbwwqxnYGYMCQGEOGK0)

![image](https://github.com/user-attachments/assets/01d5dbaa-e1e3-4b61-a5e9-5698c2a79b68)
确认下地址是否正确

**Comment by Searchld** [comment]
> > > { "ret": 401, "msg": "请求访问：/tools/getTokenId，认证失败，无法访问系统资源" }
> > 
> > 
> > ![1641721806327_ pic](https://private-user-images.githubusercontent.com/22090418/351619008-5446f982-cb74-4e51-a684-7d04a4d1a9b0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcwMzMsIm5iZiI6MTcyMTgwNjczMywicGF0aCI6Ii8yMjA5MDQxOC8zNTE2MTkwMDgtNTQ0NmY5ODItY2I3NC00ZTUxLWE2ODQtN2QwNGE0ZDFhOWIwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmQzY2UyMWRkMTg3N2RkNGE0MDE2OTllMDIyOTkyMTk2MTk5YjE2NGM1MGRiM2RhOWNiOGUzZjdlYjg1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cDmBMfvItYlRbx6v_vhaCb66CbwwqxnYGYMCQGEOGK0)
> 
> ![image](https://private-user-images.githubusercontent.com/39297195/351621209-01d5dbaa-e1e3-4b61-a5e9-5698c2a79b68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDcwNTQsIm5iZiI6MTcyMTgwNjc1NCwicGF0aCI6Ii8zOTI5NzE5NS8zNTE2MjEyMDktMDFkNWRiYWEtZTFlMy00YjYxLWE1ZTktNTY5OGMyYTc5YjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA3MzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMThmMWU4YmM3Mjg4MzljMGJmZWM2OTgwYTA1YzM3MzE3Zjk3ZWI0NTkwODZhMTIyMDQ1M2E5NzljZWVhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQVVzhSwE_2mkIgFLIwYQosbTLqz-VedNMwfMLyRNhk) 确认下地址是否正确

收到，我的锅，没仔细看下面的接口前缀，直接看文档去了
