### ISSUE TITLE
运行docker的时候报错

### ISSUE THREAD

**Issue by xiaohun254700** [Devo919/Gewechat#5]
操作系统：OpenCloudOS 9
uname -srm：Linux 6.6.34-9.oc9.x86_64 x86_64

问题一：启动docker的时候报错
已经创建了`root/temp`文件
```
[root@VM-4-14-opencloudos temp]# pwd
/root/temp
```
```
[root@VM-4-14-opencloudos lighthouse]# docker run -itd -v /root/temp:/root/temp -p 2531:2531 -p 2532:2532 --privileged=true --name=gewe gewe /usr/sbin/init
61921e87ddb80db3e62c546733f6214e61548fc3815a87b8c507274565ca5357
[root@VM-4-14-opencloudos lighthouse]# 
Message from syslogd@VM-4-14-opencloudos at Jul 25 15:37:40 ...
 systemd[1]:Failed to allocate manager object: No such file or directory
```

问题二：怎么知道服务有没有启动成功，上述报错后访问`http://ip:2532/download`无反应，浏览器提示拒绝了我们的连接请求，服务器防火墙已经开放2531和2532端口

**Comment by aw11100** [comment]
调用下api获取token，能拿到说明启动成功

**Comment by aw11100** [comment]
> 操作系统：OpenCloudOS 9 uname -srm：Linux 6.6.34-9.oc9.x86_64 x86_64
> 
> 问题一：启动docker的时候报错 已经创建了`root/temp`文件
> 
> ```
> [root@VM-4-14-opencloudos temp]# pwd
> /root/temp
> ```
> 
> ```
> [root@VM-4-14-opencloudos lighthouse]# docker run -itd -v /root/temp:/root/temp -p 2531:2531 -p 2532:2532 --privileged=true --name=gewe gewe /usr/sbin/init
> 61921e87ddb80db3e62c546733f6214e61548fc3815a87b8c507274565ca5357
> [root@VM-4-14-opencloudos lighthouse]# 
> Message from syslogd@VM-4-14-opencloudos at Jul 25 15:37:40 ...
>  systemd[1]:Failed to allocate manager object: No such file or directory
> ```
> 
> 问题二：怎么知道服务有没有启动成功，上述报错后访问`http://ip:2532/download`无反应，浏览器提示拒绝了我们的连接请求，服务器防火墙已经开放2531和2532端口

调用下api获取token，能拿到说明启动成功

**Comment by aw11100** [comment]
> 操作系统：OpenCloudOS 9 uname -srm：Linux 6.6.34-9.oc9.x86_64 x86_64
> 
> 问题一：启动docker的时候报错 已经创建了`root/temp`文件
> 
> ```
> [root@VM-4-14-opencloudos temp]# pwd
> /root/temp
> ```
> 
> ```
> [root@VM-4-14-opencloudos lighthouse]# docker run -itd -v /root/temp:/root/temp -p 2531:2531 -p 2532:2532 --privileged=true --name=gewe gewe /usr/sbin/init
> 61921e87ddb80db3e62c546733f6214e61548fc3815a87b8c507274565ca5357
> [root@VM-4-14-opencloudos lighthouse]# 
> Message from syslogd@VM-4-14-opencloudos at Jul 25 15:37:40 ...
>  systemd[1]:Failed to allocate manager object: No such file or directory
> ```
> 
> 问题二：怎么知道服务有没有启动成功，上述报错后访问`http://ip:2532/download`无反应，浏览器提示拒绝了我们的连接请求，服务器防火墙已经开放2531和2532端口

1、执行下docker ps  看下列表有没有名字为gewe的容器，有的话说明容器启动成功
2、容器启动成功后根据接口文档获取下token，能获取到代表应用启动成功

**Comment by xiaohun254700** [comment]
重装系统重试后正常了
